--- #FULL INCLUDE TASKS EXAMPLE
- hosts: db
  user: vagrant
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - include: plays/packages.yml
  - name: Verify the telnet package is installed
    raw: yum list installed | grep telnet > /home/vagrant/pkg.list
