--- # My First YAML Playbook for Ansible
- hosts: db 
  user: vagrant
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 0.1b
    author: Rethesh Nair
  vars_files:
    - conf/copyright.yml
    - conf/webdefaults.yml
  vars_prompt:
    - name: web_domain
      prompt: Web Domain
      name: pkg_name
      prompt: Install Which Package?
  tasks:
    - name: Install Apache Web Server
      action: yum name=httpd state=installed
      async: 300
      poll: 2
      notify: Restart HTTPD
    - name: Verify the {{ pkg_name }} Package to be installed
      action: yum name={{ pkg_name }} state=installed
  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
