--- #RUN ONCE
- hosts: all
  sudo: yes
  user: vagrant
  gather_facts: no
  tasks:
    - name: Run the uptime command on all hosts and log it
      raw: /usr/bin/uptime >> /home/vagrant/uptime.log
    - name: List the /var directory and log it 
      raw: ls -al /var >> /home/vagrant/dir.list
      run_once: true


