--- #onditionals
- hosts: web
  user: vagrant
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Installing Apache Web server
      yum: pkg=httpd state=latest
    - name: Verify Service Status
      shell: service httpd status
      register: result
      until: result.stdout.find("running") != -1
      retries: 5
      delay: 5
    - debug: var=result
